fortran-lang/setup-fortran

.github/workflows/test.yml, README.md, action.yml, hw.f90, setup-fortran.sh
Hi, thanks for the action. I have a few changes on a fork and wondered if you might be interested in pulling any upstream:
* expand CI test matrix across runner OS and `gcc` versions
* test runner compatibility daily ([sample run](https://github.com/w-bonelli/setup-fortran/actions/runs/3357402525))
* add runner/`gcc` version compatibility table to README
* add CI badge to README
* replace [soon-deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) set-output mechanism with [`GITHUB_OUTPUT` file](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)
* use Chocolatey to install `mingw` on Windows (considering caching this...)
* add `msys*` and `cygwin` cases for …
=> Test/document version support, miscellanous

.github/workflows/test.yml
`ubuntu-18.04` runner image is [no longer supported](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/), remove it from the test matrix
=> ci: remove ubuntu 18 from test matrix

.github/workflows/test.yml, README.md, action.yml, setup-fortran.sh
=> Add support for Intel compiler

.github/workflows/test.yml
https://github.blog/changelog/2023-04-24-github-actions-macos-13-is-now-available/
=> ci: add macos-13 to test matrix

.github/workflows/test.yml, README.md, setup-fortran.sh
Prep to support https://gcc.gnu.org/gcc-13/changes.html. ~~Not on apt/brew/choco yet, and winlibs version is still a prerelease snapshot.~~ Will update and mark ready when available on all package managers
=> Add support for GCC 13

.github/workflows/test.yml, README.md, action.yml, setup-fortran.sh
=> Update for Intel 2023.2.0

.github/workflows/test.yml, README.md
* close #39
* needs `-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib`
* update `.github/workflows/test.yml`
* document in `README.md`
* c.f.
* https://developer.apple.com/forums/thread/666700
* https://community.intel.com/t5/Intel-Fortran-Compiler/New-macOS-Big-Sur-return-quot-ld-library-not-found-for-lSystem/m-p/1235041/highlight/true#M153102
=> test(macos-13): use/suggest linker option for gcc7-9

.github/workflows/test.yml, README.md
* add badges to `README.md`
* skip CI tests if only markdown files changed
=> docs(readme): add repo status and latest tag badges

README.md
Update the example in the readme to reflect the new location of the action repository.
=> fix usage example in readme

.github/actions/test-cc/action.yml, .github/actions/test-cxx/action.yml, .github/actions/test-fc/action.yml, .github/workflows/test.yml, README.md, setup-fortran.sh, wide_compat_reports.py
* don't reinstall already-installed versions, cf #30
* factor out actions for compiler tests
* remove branch filters from push trigger
* warn c/c++ compatibility not guaranteed
=> refactor: only install toolchains if necessary, cleaner tests

action.yml
* see https://github.com/actions/cache/issues/1010
=> Leave tar as-is

.github/actions/test-cc/action.yml, .github/actions/test-cxx/action.yml, .github/actions/test-fc/action.yml, .github/workflows/test.yml, README.md, action.yml, setup-fortran.sh
Hello,
This PR refers to #52.
Within this PR, NVIDIA compiler support has been added. Please note that there is no NVIDIA compiler available for Windows and Mac.
Thanks,
Ali
=> Add NVIDIA Compiler Support

README.md
neglected in #60, can remove since macos-13/gcc7-9 no longer supported
=> docs(readme): remove outdated macos-13/gcc7-9 note

setup-fortran.sh
Bad idea carried in from [modflowpy/install-gfortran-action](https://github.com/modflowpy/install-gfortran-action/blob/55cad0f10fa0804b017a6d0169c4d4b5518b30fd/action.yml#L29), likely behind #32, blame is mine.
@gha3mi @jalvesz it would be good to confirm if pointing workflows at `wpbonelli/setup-fortran@macos-fix` solves the problem. Or provided a repo link I can fork and test
=> fix(gcc/macos): don't meddle with lib locations

.github/actions/test-cc/action.yml, .github/actions/test-cxx/action.yml, .github/actions/test-fc/action.yml, README.md, action.yml, setup-fortran.sh
* closes #59
* set `FPM_FC`, `FPM_CC`, `FPM_CXX` matching `FC`, `CC`, `CXX`
* consolidate env var assignment in setup script
=> feat: set FPM environment variables

.github/workflows/test.yml, setup-fortran.sh
Homebrew creates an unversioned symlink for `gfortran` when gcc@13 is installed, but not for `gcc` or `g++`. Might as well always create them regardless of version installed. Also the bot-created PR to update the README was not getting triggered when `test.yml` runs in reporting mode.
=> fix(mac/gcc): brew doesn't create unversioned gcc symlink

.github/workflows/test.yml
Tests already run when changes merge to `main`, no need to repeat for tags
=> ci: don't trigger when tags are pushed

action.yml
* close #69 
* fall back to `intel-classic` on macOS if `intel` selected
* README suggested we already did this but evidently not
* also, bump default `intel` version to 2024.0
=> fix(macOS/intel): fallback to intel-classic, bump default intel version

action.yml
=> fix(mac/lfortran): only install micromamba if needed

action.yml
* intel 2024.0 -> 2024.1
* lfortran 0.30.0 -> 0.33.0 &mdash; considered 0.34.0 but the [conda pkg](https://anaconda.org/conda-forge/lfortran) for osx-64 is still on 0.33.1
=> chore: bump intel and lfortran default versions

setup-fortran.sh
=> fix(mac/gcc): just brew install --force

.github/actions/test-mkl/action.yml, .github/workflows/test.yml, README.md, action.yml, install-intel-macos.sh, setup-fortran.sh, test/hw_mkl.f90
- mkl libraries included for most MacOS versions
- mkl libraries included for all linux versions
- new test for mkl installation
- currently is not the default, the mkl test is run conditionally. With the inclusion of math libraries for more compilers+OS, the tests should run as default
=> include mkl libraries for intel on linux and MacOS

.github/compat/matrix.yml, .github/workflows/test.yml, README.md, action.yml
* support gcc 14 on Linux and macOS &mdash; mingw14 not yet available from choco on Windows
* bump default intel version to 2025.0
* drop ubuntu 20.04 from test matrix (EOL)
* drop gcc < 11 from test matrix (EOL)
* add ubuntu 24.04 to test matrix
* update actions versions
=> chore: support gcc14 (mac/linux), bump default intel version

.github/compat/matrix.yml, README.md, action.yml
Hi
This PR updates the nvidia-hpc and lfortran versions to the latest.
Thanks
Ali
=> Update nvidia-hpc and lfortran versions

action.yml
Possible fix for #56. The issue seems like [incomplete oneapi environment activation](https://github.com/fortran-lang/fpm/discussions/717#discussioncomment-3091462). Previously we ran the activation script for compiler components only*. Run the root activation script instead.
@jalvesz @minhqdao let me know if pointing your workflows at this PR branch resolves the issue.
*This was carried over from https://github.com/modflowpy/install-intelfortran-action/blob/b874d3a869fb226ca5f02b4fbaffb3af7a8e6813/action.yml#L223. There was a reason we originally opted against the root activation script, but I don't recall what it was.
=> fix(oneapi): use root environment activation script

setup-fortran.sh
Currently, if you attempt to run `setup-fortran.sh` on a base Ubuntu image, if the version of `gcc` that that image is bundled with happens to be the version of `gcc` you want to install, **but** `gcc` hasn't actually been installed yet, this script will fail, as it incorrectly assumes that if the version of gcc in `apt show` matches, that `gcc` is installed. `apt show` only shows you what the packages are; it does not say what is installed. You can check what has been installed via `apt list --installed`.
Example:
```
$ docker run --rm -it ubuntu:24.04
root@e493e172c0d1:/# version=13
root@e493e172c0d1:/# apt-get update
...
Reading package lists...
root@e493e172c0d1:/# cur=$(apt show gcc | grep "Version" | cut -d':' -f3 | cut -d'-' -f1)
root@e493e172c0d1:/# maj=$(echo $cur | cut -d'.' …
```
=> Fix `gcc` install check

action.yml
Close #128.
Note, this action activates the environments for the intel toolchains, so `SETVARS_COMPLETED` and other oneapi vars will still be set when you use `compiler: intel` or `intel-classic` regardless of this option's value.
=> feat: make environment modification optional

action.yml, main.sh, setup-fortran.sh
Implementation of version: latest parsing, fixes #136 and #33
version: latest is now default for gcc and lfortran installations (since they use package managers) while also defaults to the latest "known" version for intel if explicitly specified in the workflow, e.g.
```
- uses: fortran-lang/setup-fortran@v1
with:
compiler: intel
version: latest
```
If the version option is not explicitly specified, the updated defaults are now:
```
gcc: latest
lfortran: latest
intel-classic: 2023.2.0 (pinned)
intel: 2025.0 (pinned)
nvidia-hpc: 25.1 (pinned)
```
The main changes to the logic are:
- install_gcc_brew: Uses brew install gcc without version pinning for version: latest
- install_gcc_apt: Installs gcc gfortran g++ without version pinning for version: latest
- install_gcc_choco: Install unpinned …
=> version: latest

.github/compat/matrix.yml
update the test matrix, windows-2019 runner is deprecated and windows-2025 is out
=> drop windows-2019, add windows-2025
